import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {api,key} from './api';
import Chart from './Chart';
import type {Audit,BarsResponse,Case,Draft,Retrieval,Side,State} from './types';

const actionName = (action:string) => ({FIRST:'首筆進場',ADD:'同向加倉',OPPOSITE:'反向部位',CLOSE:'平倉',SL:'停損',TP:'停利'}[action] || action);
const sourceName = (source:string) => source==='synthetic_demo'?'合成示範資料':source==='trader_history'?'交易員歷史紀錄':source==='private_audit'?'本機真實資料稽核':source==='private_market'?'第三方歷史行情':source;
const sideName = (side:Side) => side==='BUY'?'買進':'賣出';
const gainClass = (value:string|null|undefined) => value?.startsWith('-')?'negative':'positive';
const EMPTY_BARS:BarsResponse = {bars:[],markers:[],source:'',interval:'5m'};
const currencyName = (currency?:string) => !currency || /NOT_STATED|UNKNOWN/.test(currency)?'幣別未確認':currency;
const formatTime = (value?:string|number) => typeof value==='number'?`${new Date(value*1000).toISOString().replace('T',' ').slice(0,19)} UTC`:value||'—';
const behaviorName = (value:string) => ({NO_OBSERVED_POSITION:'可見首筆：當時未觀察到既有黃金持倉',ADVERSE_ADD:'價格逆向加單候選',FAVORABLE_ADD:'價格順向加單候選',TIME_TIE:'同分鐘操作順序未確認'}[value] || value);
const getAction = (state:State|null,side:Side) => !state?.positions.length?'FIRST':state.positions.every(p=>p.side===side)?'ADD':'OPPOSITE';

function Pool({pool}:{pool:Retrieval}) {
  return <div className="pool"><div className="pool-summary"><span>完整匹配池 <b>{pool.total}</b></span><span className="positive">獲利 {pool.wins}</span><span className="negative">虧損 {pool.losses}</span><span>持平 {pool.flat} · 未知 {pool.unknown}</span></div><p className="fine">歷史獲利比例 {pool.win_rate===null?'資料不足':`${pool.win_rate}%`}，僅描述匹配池，不是本次交易成功機率。展示虧損案例優先；盈虧不參與相似度排序。</p></div>;
}
function CaseRows({cases,onOpen}:{cases:Case[];onOpen:(id:string)=>void}) {
  return <div className="table-scroll"><table><thead><tr><th>案例／來源</th><th>操作</th><th>手數</th><th>事後損益／幣別</th><th>匹配依據</th><th/></tr></thead><tbody>{cases.map(c=><tr key={c.id}><td><strong>{c.label}</strong><small>{sourceName(c.source_kind)} · {c.time_alignment==='confirmed'?'時區已核對':'時區未確認'}</small></td><td><span className={c.side==='BUY'?'positive':'negative'}>{sideName(c.side)}</span> · {actionName(c.action)}</td><td className="number">{c.lot}</td><td className={`number ${gainClass(c.profit)}`}>{c.profit}<small>{currencyName(c.currency)}</small></td><td className="case-reasons">{c.match_reasons.join('、') || '條件資料不足'}</td><td><button className="text-button" onClick={()=>onOpen(c.id)} aria-label={`查看 ${c.label}`}>查看 ↗</button></td></tr>)}</tbody></table>{cases.length===0&&<div className="empty">目前沒有已成熟且可匹配的案例。仍可用價格情境檢查擬下單風險。</div>}</div>;
}

export default function App() {
  const [state,setState]=useState<State|null>(null),[bars,setBars]=useState<BarsResponse>(EMPTY_BARS),[audit,setAudit]=useState<Audit|null>(null),[pool,setPool]=useState<Retrieval|null>(null);
  const [interval,setInterval]=useState('5m'),[side,setSide]=useState<Side>('BUY'),[lot,setLot]=useState('0.10'),[sl,setSl]=useState(''),[tp,setTp]=useState('');
  const [rightTab,setRightTab]=useState<'order'|'chat'>('order'),[bottomTab,setBottomTab]=useState('positions'),[draft,setDraft]=useState<Draft|null>(null),[selectedCase,setSelectedCase]=useState<Case|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[light,setLight]=useState(()=>localStorage.getItem('gold-theme')==='light'),[message,setMessage]=useState('');
  const [chat,setChat]=useState<{role:'user'|'assistant';text:string}[]>([]);
  const reviewDialog=useRef<HTMLDialogElement>(null),caseDialog=useRef<HTMLDialogElement>(null),confirmKey=useRef({draft:'',key:''});
  const task=useCallback(async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(e instanceof Error?e.message:'操作失敗，請重試。');}finally{setBusy(false);}},[]);
  const bootstrap=useCallback(()=>task(async()=>{const [next,a]=await Promise.all([api<State>('/state'),api<Audit>('/audit')]);setState(next);setAudit(a);}),[task]);
  useEffect(()=>{void bootstrap();},[bootstrap]);
  useEffect(()=>{document.documentElement.dataset.theme=light?'light':'dark';localStorage.setItem('gold-theme',light?'light':'dark');},[light]);
  useEffect(()=>{if(!state)return;let cancelled=false;api<BarsResponse>(`/bars?interval=${interval}`).then(value=>{if(!cancelled)setBars(value);}).catch(e=>{if(!cancelled)setError(e.message);});return ()=>{cancelled=true;};},[state?.version,interval]);
  useEffect(()=>{if(!state)return;let cancelled=false;const timeout=window.setTimeout(()=>{const action=getAction(state,side);api<Retrieval>(`/cases?side=${side}&action=${action}&lot=${encodeURIComponent(lot || '0.10')}`).then(value=>{if(!cancelled)setPool(value);}).catch(()=>{if(!cancelled)setPool(null);});},250);return ()=>{cancelled=true;window.clearTimeout(timeout);};},[state?.version,side,lot]);
  useEffect(()=>{const dialog=reviewDialog.current;if(draft){confirmKey.current={draft:draft.id,key:key()};if(!dialog?.open)dialog?.showModal();}else if(dialog?.open)dialog.close();},[draft]);
  useEffect(()=>{const dialog=caseDialog.current;if(selectedCase){if(!dialog?.open)dialog?.showModal();}else if(dialog?.open)dialog.close();},[selectedCase]);
  const cancelDraft=()=>task(async()=>{if(draft)await api(`/drafts/${draft.id}/cancel`,{});setDraft(null);});
  const makeDraft=(e:FormEvent)=>{e.preventDefault();void task(async()=>{setDraft(await api<Draft>('/drafts',{side,lot,sl:sl.trim()||null,tp:tp.trim()||null}));});};
  const confirmDraft=()=>task(async()=>{if(!draft)return;const result=await api<{state:State;order_id:string}>(`/drafts/${draft.id}/confirm`,{revision:draft.revision,idempotency_key:confirmKey.current.key});setState(result.state);setDraft(null);setBottomTab('positions');setNotice(`已記錄本機回放成交 · ${result.order_id}`);});
  const replay=(count:number)=>task(async()=>{setState(await api<State>('/replay/step',{bars:count}));});
  const reset=()=>{if(!window.confirm('重設回放會清除目前本機模擬持倉與成交紀錄。要重新開始嗎？'))return;void task(async()=>{setState(await api<State>('/replay/reset',{}));setNotice('回放已重設。');});};
  const closePosition=(id:string)=>{if(!window.confirm('確認以目前可見報價平倉這筆本機模擬部位？'))return;void task(async()=>{const result=await api<{state:State}>(`/positions/${id}/close`,{confirmed:true,idempotency_key:key()});setState(result.state);setNotice('已完成本機模擬平倉。');});};
  const openCase=(id:string)=>task(async()=>{
    const ranked=draft?.retrieval.cases.find(c=>c.id===id)||pool?.cases.find(c=>c.id===id);
    const detail=await api<Case>(`/cases/${encodeURIComponent(id)}`);
    setSelectedCase({...detail,match_reasons:ranked?.match_reasons||[],differences:ranked?.differences||[],distance:ranked?.distance??null});
  });
  const sendChat=(e:FormEvent)=>{e.preventDefault();if(!message.trim())return;const sent=message.trim();setChat(items=>[...items,{role:'user',text:sent}]);setMessage('');void task(async()=>{const result=await api<{message:string;draft:Draft|null;provider:string}>('/chat',{message:sent,lot,side});setChat(items=>[...items,{role:'assistant',text:result.message}]);if(result.draft){setSide(result.draft.side);setLot(result.draft.lot);setSl(result.draft.sl||'');setTp(result.draft.tp||'');setDraft(result.draft);}});};
  const connected=state?.mode==='replay'||state?.broker_connected;
  const currentAction=getAction(state,side);
  return <div className="terminal">
    <header className="topbar"><div className="brand"><span className="brand-mark">Au</span><strong>Gold Desk</strong><span className="brand-caption">黃金交易工作台</span></div><div className="header-tools"><label className="sr-only" htmlFor="mode">交易模式</label><select id="mode" value={state?.mode||'replay'} disabled={busy||!state} onChange={e=>void task(async()=>{setState(await api<State>('/mode',{mode:e.target.value}));})}><option value="replay">歷史回放</option><option value="broker_demo">券商模擬帳戶</option></select><button className="theme-button" onClick={()=>setLight(v=>!v)} aria-label={light?'切換深色':'切換淺色'}>{light?'深色':'淺色'}</button><span className="connection"><i className={state?'status-dot':'status-dot offline'}/>{state?.mode==='broker_demo'?'券商未連線':state?'本機回放':'連接中'}</span></div></header>
    <div className="source-strip"><span className="source-label">{state?sourceName(state.data_source):'資料載入中'}</span><span>{state?.mode==='broker_demo'?'尚未設定券商 demo；此模式無法送出訂單。':'行情依回放時間推進，成交為本機模擬。'}</span><time>{formatTime(state?.clock)}</time></div>
    {(error||notice)&&<div className={`feedback ${error?'error':'success'}`} role={error?'alert':'status'}><span>{error||notice}</span>{!state&&<button onClick={()=>void bootstrap()} disabled={busy}>重新連線</button>}<button className="text-button" aria-label="關閉通知" onClick={()=>{setError('');setNotice('');}}>×</button></div>}
    <div className="workspace">
      <main className="market-panel" aria-label="行情與回放">
        <div className="instrument-header"><div><h1>XAU / USD <span>現貨黃金</span></h1><div className="market-subtitle">每手 100 oz · USD 計價</div></div><div className="quotes"><div><span>賣出價 BID</span><b className="negative">{state?.quote.bid||'—'}</b></div><div><span>買進價 ASK</span><b className="positive">{state?.quote.ask||'—'}</b></div></div></div>
        <div className="chart-toolbar"><div className="segments" aria-label="K 線週期">{['5m','15m','1h'].map(value=><button key={value} aria-pressed={interval===value} className={interval===value?'active':''} onClick={()=>setInterval(value)}>{value==='1h'?'1 小時':value==='5m'?'5 分':'15 分'}</button>)}</div><div className="legend"><span><i className="ma20"/>MA 20</span><span><i className="ma60"/>MA 60</span><span>已收盤 K 線</span></div></div>
        <div className="chart-area">{bars.bars.length?<Chart bars={bars.bars} markers={bars.markers} light={light}/>:<div className="chart-loading">{state?'此資料來源尚無可用行情。':'等待本機行情服務…'}</div>}</div>
        <div className="market-stats"><span>區間變動 <b className={gainClass(state?.market.change_pct)}>{state?.market.change_pct||'—'}%</b></span><span>區間高 <b>{state?.market.high||'—'}</b></span><span>區間低 <b>{state?.market.low||'—'}</b></span><span>波動區間 <b>{state?.market.range_pct||'—'}%</b></span><span className="chart-source">{bars.source?sourceName(bars.source):'—'}</span></div>
        <div className="replay-toolbar"><div className="replay-title"><span className="status-dot"/>回放控制<span className="fine">僅顯示決策當時可見行情</span></div><div className="replay-buttons"><button disabled={busy||!state||state.mode!=='replay'} onClick={()=>void replay(1)}>下一根 <span>＋5m</span></button><button disabled={busy||!state||state.mode!=='replay'} onClick={()=>void replay(6)}>＋30 分</button><button disabled={busy||!state||state.mode!=='replay'} onClick={()=>void replay(12)}>＋1 小時</button><button className="text-button" disabled={busy||!state||state.mode!=='replay'} onClick={reset}>重設</button></div></div>
      </main>
      <aside className="order-panel" aria-label="訂單與對話"><div className="tabs right-tabs">{[['order','下單'],['chat','對話助手']].map(([value,label])=><button key={value} className={rightTab===value?'active':''} aria-pressed={rightTab===value} onClick={()=>setRightTab(value as 'order'|'chat')}>{label}</button>)}</div><div className="account-strip"><span>模擬淨值 <b>{state?.account.equity||'—'} <small>USD</small></b></span><span>餘額 <b>{state?.account.balance||'—'}</b></span></div>
      {rightTab==='order'?<form className="order-form" onSubmit={makeDraft}><div className="section-caption">市價訂單 <span>{actionName(currentAction)}</span></div><div className="side-switch"><button type="button" className={side==='SELL'?'selected sell':'sell'} aria-pressed={side==='SELL'} onClick={()=>setSide('SELL')}>賣出 SELL<span>{state?.quote.bid||'—'}</span></button><button type="button" className={side==='BUY'?'selected buy':'buy'} aria-pressed={side==='BUY'} onClick={()=>setSide('BUY')}>買進 BUY<span>{state?.quote.ask||'—'}</span></button></div><label htmlFor="lot">交易手數 <span>Lot</span></label><input id="lot" type="number" min="0.01" max="100" step="0.01" required value={lot} onChange={e=>setLot(e.target.value)}/><div className="two-fields"><div><label htmlFor="sl">停損 <span>選填</span></label><input id="sl" type="number" min="0.01" step="0.01" placeholder="未設定" value={sl} onChange={e=>setSl(e.target.value)}/></div><div><label htmlFor="tp">停利 <span>選填</span></label><input id="tp" type="number" min="0.01" step="0.01" placeholder="未設定" value={tp} onChange={e=>setTp(e.target.value)}/></div></div><div className="order-explainer"><span className="step-label">下單前檢查</span><p>先核對相似歷史案例與部位變化，再確認成交。沒有停損時，顯示價格情境損失。</p></div><button className="primary full" disabled={busy||!connected||!state}>{busy?'處理中…':`${actionName(currentAction)} · 檢查訂單`}</button><p className="fine">{state?.mode==='broker_demo'?'券商 demo 尚未連線，訂單已停用。':'將以回放報價在本機模擬成交。'}</p></form>:<div className="chat-panel"><div className="provider-label">{state?.llm_enabled?'已設定 LLM':'本機規則解析 · LLM 未設定'}</div><div className="chat-log" role="log" aria-live="polite">{chat.length===0?<div className="chat-intro"><h2>把想做的交易說清楚</h2><p>助手可以說明盤面、試算風險，並建立待確認草稿。</p><button onClick={()=>setMessage('買進 0.10 手')}>買進 0.10 手</button><button onClick={()=>setMessage('分析目前行情與風險')}>分析目前行情與風險</button><p className="fine">草稿仍會進入同一份案例與風險檢查。</p></div>:chat.map((item,index)=><div className={`chat-message ${item.role}`} key={index}><span>{item.role==='user'?'你':'助手'}</span><p>{item.text}</p></div>)}</div><form onSubmit={sendChat} className="chat-input"><label htmlFor="message" className="sr-only">輸入交易指令或問題</label><textarea id="message" value={message} onChange={e=>setMessage(e.target.value)} placeholder="例如：買進 0.10 手，或詢問部位風險" rows={3}/><button className="primary" disabled={busy||!message.trim()||!state}>送出</button></form></div>}
      </aside>
      <section className="bottom-panel" aria-label="帳戶與案例資料"><div className="bottom-heading"><div className="tabs">{[['positions',`持倉 ${state?.positions.length||0}`],['history','成交紀錄'],['cases','相似案例'],['audit','資料分群']].map(([value,label])=><button key={value} className={bottomTab===value?'active':''} aria-pressed={bottomTab===value} onClick={()=>setBottomTab(value)}>{label}</button>)}</div><span className="fine">本機展示帳戶 · USD</span></div>
      {bottomTab==='positions'&&<div className="table-scroll"><table><thead><tr><th>商品／時間</th><th>方向</th><th>手數</th><th>進場價</th><th>停損</th><th>停利</th><th>浮動損益 USD</th><th/></tr></thead><tbody>{state?.positions.map(p=><tr key={p.id}><td><strong>XAUUSD</strong><small>{formatTime(p.opened_at)}</small></td><td className={p.side==='BUY'?'positive':'negative'}>{sideName(p.side)}</td><td className="number">{p.lot}</td><td className="number">{p.entry}</td><td className="number">{p.sl||'—'}</td><td className="number">{p.tp||'—'}</td><td className={`number ${gainClass(p.pnl)}`}>{p.pnl}</td><td><button className="close-button" disabled={busy||!connected} onClick={()=>closePosition(p.id)}>平倉</button></td></tr>)}</tbody></table>{!state?.positions.length&&<div className="empty"><strong>目前沒有本機模擬持倉</strong><span>選擇買進或賣出、輸入手數，按「首筆進場 · 檢查訂單」開始。</span></div>}</div>}
      {bottomTab==='history'&&<div className="table-scroll"><table><thead><tr><th>成交編號／時間</th><th>方向</th><th>操作</th><th>手數</th><th>成交價</th><th>狀態</th><th>已實現損益 USD</th></tr></thead><tbody>{state?.orders.slice().reverse().map(o=><tr key={o.id}><td><strong>{o.id}</strong><small>{formatTime(o.time)}</small></td><td className={o.side==='BUY'?'positive':'negative'}>{sideName(o.side)}</td><td>{actionName(o.action)}</td><td className="number">{o.lot}</td><td className="number">{o.price}</td><td>{o.status==='FILLED'?'本機模擬成交':o.status}</td><td className={`number ${o.pnl?gainClass(o.pnl):''}`}>{o.pnl||'—'}</td></tr>)}</tbody></table>{!state?.orders.length&&<div className="empty">成交後可在此查看進場、加倉與平倉紀錄。</div>}</div>}
      {bottomTab==='cases'&&<div>{pool?<><Pool pool={pool}/><CaseRows cases={pool.cases} onOpen={id=>void openCase(id)}/><div className="limitations">{pool.limitations.map((text,index)=><p key={index}>{text}</p>)}</div></>:<div className="empty">案例檢索尚未完成；請確認服務與手數輸入。</div>}</div>}
      {bottomTab==='audit'&&<div className="audit-content">{audit?<><div className="audit-summary"><span>{sourceName(audit.source)}</span><span>來源檔 {audit.source_files}</span><span>黃金紀錄 {audit.total_gold_records}</span><span>期間 {typeof audit.period==='string'?audit.period:JSON.stringify(audit.period)}</span></div><div className="table-scroll"><table><thead><tr><th>分群</th><th>數量</th><th>定義與用途</th></tr></thead><tbody>{audit.groups.map(g=><tr key={g.code}><td><strong>{g.label}</strong><small>{g.code}</small></td><td className="number">{g.count}</td><td className="audit-description">{g.description}</td></tr>)}</tbody></table></div><div className="limitations">{[...audit.limitations,...(state?.data_quality||[])].map((text,index)=><p key={index}>{text}</p>)}<p>更新時間：{audit.refreshed_at}</p></div></>:<div className="empty">資料分群尚未載入。</div>}</div>}
      </section>
    </div>
    <footer><span>Gold Trading Project</span><span>案例檢索 + 風險試算 · 示範版本 1.0</span><span>無真實資金交易</span></footer>
    <dialog ref={reviewDialog} className="review-dialog" onCancel={e=>{e.preventDefault();void cancelDraft();}} aria-labelledby="review-title">{draft&&<><div className="dialog-heading"><div><span className="fine">成交前確認</span><h2 id="review-title">{actionName(draft.action)} · {sideName(draft.side)} {draft.lot} 手</h2></div><button className="text-button" autoFocus disabled={busy} onClick={()=>void cancelDraft()} aria-label="取消草稿">×</button></div><div className="dialog-body"><div className="review-order"><span>擬成交價 <b>{draft.price}</b></span><span>停損 <b>{draft.sl||'未設定'}</b></span><span>停利 <b>{draft.tp||'未設定'}</b></span><span>來源 <b>{state?.mode==='replay'?'本機歷史回放':'券商 demo'}</b></span></div><h3>部位與價格風險</h3><div className="risk-grid"><span>總手數<b>{draft.risk.before_lot} → {draft.risk.after_lot}</b></span><span>同方向均價<b>{draft.risk.average_entry}</b></span><span>本筆停損情境損失 USD<b>{draft.risk.stop_loss_usd ?? '未設定停損'}</b></span><span>本筆風險報酬比<b>{draft.risk.reward_risk ?? '資料不足'}</b></span></div><div className="scenario-row">{draft.risk.scenarios.map((s,index)=><span key={index}>價格移動 {s.move}<b className={s.loss.startsWith('-')?'positive':'negative'}>{s.loss.startsWith('-')?'獲利':'損失'} {s.loss.startsWith('-')?s.loss.slice(1):s.loss} USD</b></span>)}</div>{draft.risk.warnings.length>0&&<div className="warning-box">{draft.risk.warnings.map((w,index)=><p key={index}>{w}</p>)}</div>}<h3>相似歷史案例</h3><Pool pool={draft.retrieval}/><CaseRows cases={draft.retrieval.cases} onOpen={id=>void openCase(id)}/><div className="limitations">{draft.retrieval.limitations.map((text,index)=><p key={index}>{text}</p>)}</div><h3>條件式說明</h3><p className="explanation">{draft.explanation}</p>{error&&<p className="modal-error" role="alert">{error}</p>}</div><div className="dialog-actions"><p>確認後由後端再次檢查草稿與回放版本。</p><button disabled={busy} onClick={()=>void cancelDraft()}>取消草稿</button><button className="primary" disabled={busy||!connected} onClick={()=>void confirmDraft()}>{busy?'處理中…':state?.mode==='replay'?'確認本機模擬成交':'確認 demo 訂單'}</button></div></>}</dialog>
    <dialog ref={caseDialog} className="case-dialog" onCancel={()=>setSelectedCase(null)} aria-labelledby="case-title">{selectedCase&&<><div className="dialog-heading"><div><span className="fine">{sourceName(selectedCase.source_kind)} · {selectedCase.time_alignment==='confirmed'?'時區已核對':'時區未確認'}</span><h2 id="case-title">{selectedCase.label}</h2></div><button autoFocus className="text-button" onClick={()=>setSelectedCase(null)} aria-label="關閉案例">×</button></div><div className="dialog-body"><div className="case-overview"><span>{sideName(selectedCase.side)} · {actionName(selectedCase.action)}</span><span>{selectedCase.opened_at} → {selectedCase.closed_at}</span><strong className={gainClass(selectedCase.profit)}>{selectedCase.profit} {currencyName(selectedCase.currency)}</strong></div>{selectedCase.bars?.length?<div className="case-chart"><Chart bars={selectedCase.bars} markers={selectedCase.markers} light={light}/></div>:<div className="unavailable-chart"><strong>此案例沒有已核對的 K 線</strong><p>{selectedCase.chart_unavailable_reason||selectedCase.chart_reason||'資料源未提供可核對時區與成交位置的 OHLC，僅呈現原始操作序列。'}</p></div>}<p className="explanation">{behaviorName(selectedCase.behavior)}</p><details className="distance-details"><summary>操作條件距離 {selectedCase.distance ?? '未提供'} · 檢索說明</summary><p>目前比較買賣方向、首筆／加倉及手數等可核對操作條件；數值越小條件越接近。盤面未完成時區對齊時，沒有納入 K 線相似度；事後盈虧只決定展示次序。</p></details><h3>可見操作序列 {selectedCase.sequence_total&&selectedCase.sequence_total>selectedCase.sequence.length?<small>（顯示 {selectedCase.sequence.length} / {selectedCase.sequence_total} 筆）</small>:null}</h3><div className="table-scroll"><table><thead><tr><th>順序</th><th>角色</th><th>方向</th><th>手數</th><th>進場</th><th>平倉</th><th>損益／幣別</th></tr></thead><tbody>{selectedCase.sequence.map(s=><tr key={s.index}><td>{s.ordering_uncertain?'待確認':s.index}</td><td>{actionName(s.role)}</td><td>{sideName(s.side)}</td><td className="number">{s.lot}</td><td className="number">{s.entry}</td><td className="number">{s.exit}</td><td className={`number ${gainClass(s.profit)}`}>{s.profit}<small>{currencyName(selectedCase.currency)}</small></td></tr>)}</tbody></table></div><h3>相同與不同條件</h3><p>{selectedCase.match_reasons.join('；')}</p><div className="limitations">{selectedCase.differences.map((d,index)=><p key={index}>{d}</p>)}<p>操作群是候選；可見首筆不代表已確認空手。案例結果為事後資料。</p></div></div><div className="dialog-actions"><button className="primary" onClick={()=>setSelectedCase(null)}>返回交易工作台</button></div></>}</dialog>
  </div>;
}



